### ISSUE TITLE
Targeting API 31 while running on API 31 crashes

### ISSUE THREAD

**Issue by mattinger** [TonyTangAndroid/Wood#24]
If you target API 31 and then run on an API 31 (Android 12) device, you will get the following error:

```
    java.lang.IllegalArgumentException: xxxx: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
        at android.app.PendingIntent.getActivity(PendingIntent.java:444)
        at android.app.PendingIntent.getActivity(PendingIntent.java:408)
        at com.tonytangandroid.wood.NotificationHelper.show(NotificationHelper.java:62)
        at com.tonytangandroid.wood.WoodTree.create(WoodTree.java:184)
        at com.tonytangandroid.wood.WoodTree.doLog(WoodTree.java:176)
        at com.tonytangandroid.wood.WoodTree.access$000(WoodTree.java:18)
        at com.tonytangandroid.wood.WoodTree$1.run(WoodTree.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

I believe this function in NotificationHelper.java needs updating:

```
    public synchronized void show(Leaf transaction, boolean stickyNotification) {
        addToBuffer(transaction);
        NotificationCompat.Builder builder = new NotificationCompat.Builder(mContext, CHANNEL_ID)
                .setContentIntent(PendingIntent.getActivity(mContext, 0, Wood.getLaunchIntent(mContext), 0))
                .setLocalOnly(true)
                .setSmallIcon(R.drawable.wood_icon)
                .setColor(ContextCompat.getColor(mContext, R.color.wood_colorPrimary))
                .setOngoing(stickyNotification)
                .setContentTitle(mContext.getString(R.string.wood_notification_title));
        NotificationCompat.InboxStyle inboxStyle = new NotificationCompat.InboxStyle();

        int count = 0;
        for (int i = TRANSACTION_BUFFER.size() - 1; i >= 0; i--) {
            if (count < BUFFER_SIZE) {
                if (count == 0) {
                    builder.setContentText(getNotificationText(TRANSACTION_BUFFER.valueAt(i)));
                }
                inboxStyle.addLine(getNotificationText(TRANSACTION_BUFFER.valueAt(i)));
            }
            count++;
        }
        builder.setAutoCancel(true);
        builder.setStyle(inboxStyle);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            builder.setSubText(String.valueOf(TRANSACTION_COUNT));
        } else {
            builder.setNumber(TRANSACTION_COUNT);
        }
        builder.addAction(getDismissAction());
        builder.addAction(getClearAction());
        mNotificationManager.notify(CHANNEL_ID.hashCode(), builder.build());
    }
    
```

**Comment by mattinger** [comment]
FYI:  There's a quick fix to this when you initialize the tree:

```
            WoodTree(this)
                .retainDataFor(WoodTree.Period.FOREVER)
                .maxLength(100000)
                .apply {
                    if (Build.VERSION.SDK_INT < 31) {
                        showNotification(true)
                    }
                }
```

**Comment by TonyTangAndroid** [comment]
Please update to the latest version to resolve the problem.

```
debugImplementation 'com.github.TonyTangAndroid.Wood:wood:0.9.9.1'
releaseImplementation 'com.github.TonyTangAndroid.Wood:wood-no-op:0.9.9.1'
```
